name: Documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
  workflow_dispatch:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: write
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Build and deploy Documenter.jl docs
        env:
          GKSwstype: nul # turn off GR's interactive plotting for notebooks
        uses: TuringLang/actions/DocsDocumenter@main
        with:
          julia-version: '1'
          navbar-url: https://raw.githubusercontent.com/JuliaGaussianProcesses/.github/refs/heads/main/DocumenterNavbar/JuliaGPNavbar.html
